#!/bin/bash 

BUILDMODE=$1

echo Building Micro-Manger, mode: $BUILDMODE
echo

echo Building MMCore:
pushd MMCore
make $BUILDMODE
popd

echo Building DeviceAdapters:
echo
 
echo Building AVTCamera:
pushd AVTCamera
make $BUILDMODE
popd

 

popd

echo Building MMCoreJ_wrap:
pushd MMCoreJ_wrap
make $BUILDMODE
popd

echo Building MMCorePy_wrap:
pushd MMCorePy_wrap
#make $BUILDMODE
popd

echo Building Micro-Manger Studio:
pushd mmstudio
ant -buildfile build32.xml install
popd

 
echo Building MTTracker:
pushd plugins/MTTracker
ant -buildfile build.xml build
popd
