/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_MMCoreJ_WRAP_H_
#define SWIG_MMCoreJ_WRAP_H_

class SwigDirector_MMEventCallback : public MMEventCallback, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_MMEventCallback(JNIEnv *jenv);
    virtual ~SwigDirector_MMEventCallback();
    virtual void onPropertiesChanged();
    virtual void onPropertyChanged(char const *name, char const *propName, char const *propValue);
    virtual void onConfigGroupChanged(char const *groupName, char const *newConfigName);
    virtual void onPixelSizeChanged(double newPixelSizeUm);
    virtual void onStagePositionChanged(char *name, double pos);
    virtual void onStagePositionChangedRelative(char *name, double pos);
    virtual void onXYStagePositionChanged(char *name, double xpos, double ypos);
    virtual void onXYStagePositionChangedRelative(char *name, double xpos, double ypos);
    virtual void onExposureChanged(char *name, double newExposure);
public:
    bool swig_overrides(int n) {
      return (n < 9 ? swig_override[n] : false);
    }
protected:
    bool swig_override[9];
};


#endif
